server:
  port: 8881
  servlet:
    context-path: /auth

#security: 
#  oauth2: 
#    client:
#      client-id: springdeveloper123
#      client-secret: test
#      authorized-grant-types: refresh_token, password, authorization_code 
#      scope: read, write
#      access-token-validity-seconds: 600
#      refresh-token-validity-seconds: 1200
#    resource:
#      jwt:
#        key-value: secretkey 
  

#H2 database settings
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/abv_test
  jpa:    
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: true
        use_sql_comments: true
        format_sql: true
