server:
  port: 8002
  servlet:
    context-path: /resource
    
    
spring: 
  security:
    user:
      name: john
      password: john
      roles:
      - USER
          
security:
  oauth2:
    resource:
      jwt:
        key-value: secretkey